"""
nnU-Net Augmented — Segmentation model trained on real + synthetic MRI data.

This package contains the augmented segmentation U-Net trained on both
real MRI data and synthetic data generated by the pix2pix GAN for
Experiment B comparison.
"""
