"""mask-to-mri — Synthetic MRI Generation with pix2pix."""

# Re-export pix2pix components for backward compatibility
from .pix2pix import (
    UNetGenerator,
    create_generator,
    weights_init_normal,
    PatchGANDiscriminator,
    create_discriminator,
    GANLoss,
    PerceptualLoss,
    L1Loss,
    DiceLoss,
    DiceBCELoss,
    discriminator_loss_real,
    discriminator_loss_fake,
    generator_adversarial_loss,
    train,
    load_checkpoint,
    find_latest_checkpoint,
    load_metrics,
    compute_ssim,
    compute_ssim_batch,
    compute_psnr,
    compute_psnr_batch,
    compute_fid_from_paths,
    compute_dice_score,
    save_eval_results,
    load_config,
    fix_seed,
    setup_logger,
    get_device,
    count_parameters,
    print_model_summary,
    make_sample_grid,
    plot_loss_curves,
    plot_metrics_from_file,
)

__all__ = [
    # Generator
    "UNetGenerator",
    "create_generator",
    "weights_init_normal",
    # Discriminator
    "PatchGANDiscriminator",
    "create_discriminator",
    # Losses
    "GANLoss",
    "PerceptualLoss",
    "L1Loss",
    "DiceLoss",
    "DiceBCELoss",
    "discriminator_loss_real",
    "discriminator_loss_fake",
    "generator_adversarial_loss",
    # Training
    "train",
    "load_checkpoint",
    "find_latest_checkpoint",
    "load_metrics",
    # Evaluation
    "compute_ssim",
    "compute_ssim_batch",
    "compute_psnr",
    "compute_psnr_batch",
    "compute_fid_from_paths",
    "compute_dice_score",
    "save_eval_results",
    # Utilities
    "load_config",
    "fix_seed",
    "setup_logger",
    "get_device",
    "count_parameters",
    "print_model_summary",
    "make_sample_grid",
    "plot_loss_curves",
    "plot_metrics_from_file",
]
