"""mask-to-mri — Synthetic MRI Generation with pix2pix and DDPM."""

# Re-export pix2pix components for backward compatibility
from .pix2pix import (
    UNetGenerator,
    create_generator,
    weights_init_normal,
    PatchGANDiscriminator,
    create_discriminator,
    GANLoss,
    PerceptualLoss,
    L1Loss,
    DiceLoss,
    DiceBCELoss,
    discriminator_loss_real,
    discriminator_loss_fake,
    generator_adversarial_loss,
    train,
    load_checkpoint,
    find_latest_checkpoint,
    load_metrics,
    compute_ssim,
    compute_ssim_batch,
    compute_psnr,
    compute_psnr_batch,
    compute_fid_from_paths,
    compute_dice_score,
    save_eval_results,
    load_config,
    fix_seed,
    setup_logger,
    get_device,
    count_parameters,
    print_model_summary,
    make_sample_grid,
    plot_loss_curves,
    plot_metrics_from_file,
)

# Re-export med_ddpm components
from .med_ddpm import (
    ConditionalUNet,
    create_unet,
    SinusoidalTimeEmbedding,
    DDPM,
    linear_beta_schedule,
    cosine_beta_schedule,
    DDPMConditionalDataset,
    build_ddpm_dataloaders,
    train as ddpm_train,
    EMA,
    find_latest_ddpm_checkpoint,
    load_ddpm_checkpoint,
    load_ddpm_metrics,
    generate_from_masks,
    generate_and_save,
    load_model_for_sampling,
)

__all__ = [
    # pix2pix — Generator
    "UNetGenerator",
    "create_generator",
    "weights_init_normal",
    # pix2pix — Discriminator
    "PatchGANDiscriminator",
    "create_discriminator",
    # pix2pix — Losses
    "GANLoss",
    "PerceptualLoss",
    "L1Loss",
    "DiceLoss",
    "DiceBCELoss",
    "discriminator_loss_real",
    "discriminator_loss_fake",
    "generator_adversarial_loss",
    # pix2pix — Training
    "train",
    "load_checkpoint",
    "find_latest_checkpoint",
    "load_metrics",
    # pix2pix — Evaluation
    "compute_ssim",
    "compute_ssim_batch",
    "compute_psnr",
    "compute_psnr_batch",
    "compute_fid_from_paths",
    "compute_dice_score",
    "save_eval_results",
    # pix2pix — Utilities
    "load_config",
    "fix_seed",
    "setup_logger",
    "get_device",
    "count_parameters",
    "print_model_summary",
    "make_sample_grid",
    "plot_loss_curves",
    "plot_metrics_from_file",
    # med_ddpm — U-Net
    "ConditionalUNet",
    "create_unet",
    "SinusoidalTimeEmbedding",
    # med_ddpm — DDPM
    "DDPM",
    "linear_beta_schedule",
    "cosine_beta_schedule",
    # med_ddpm — Dataset
    "DDPMConditionalDataset",
    "build_ddpm_dataloaders",
    # med_ddpm — Training
    "ddpm_train",
    "EMA",
    "find_latest_ddpm_checkpoint",
    "load_ddpm_checkpoint",
    "load_ddpm_metrics",
    # med_ddpm — Sampling
    "generate_from_masks",
    "generate_and_save",
    "load_model_for_sampling",
]
